# -*- coding: utf-8 -*-
"""kaithiTranslator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjtzOHPEHryN3PY4RuGt2GjD3BndHiTs
"""

!pip install -U langchain-community

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U --quiet langchain-google-genai langchain faiss-cpu pypdf sentence-transformers

import os
import pandas as pd
from langchain.document_loaders import PyPDFLoader
from langchain.embeddings import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.vectorstores import FAISS  # Optional, in case you need for retrieval

# ✅ Set up your Google Gemini API Key
os.environ["GOOGLE_API_KEY"] = "AIzaSyA68faIW7NMuwOnvXzQPcisiIez6Qlmn2E"

# ✅ Load CSV File
file_path = '/content/eng_hin_kaithi.csv'
df = pd.read_csv(file_path)
print(df.head())

# ✅ Create Dictionary Mapping
eng_to_kaithi = dict(zip(df['English'], df['Kaithi']))

# ✅ Translate via Local CSV Lookup
def translate_to_kaithi(word):
    return eng_to_kaithi.get(word, None)

# ✅ Set up Gemini Model
llm = ChatGoogleGenerativeAI(model="gemini-pro")

# ✅ Translate via Gemini (if not found in CSV)
def translate_with_gemini(word):
    prompt = f"Translate the following English word to the Kaithi script: {word}"
    response = llm.generate_content(prompt)
    return response.text.strip()

# ✅ CLI Bot Loop
def bot_translate_to_kaithi():
    print("🔤 Welcome to the English ➡️ Kaithi Translator Bot!")
    while True:
        user_input = input("🔍 Enter an English word (or type 'exit' to quit): ").strip()
        if user_input.lower() == 'exit':
            print("👋 Bye! Nice to meet you.")
            break

        # Try local CSV lookup first
        kaithi_translation = translate_to_kaithi(user_input)
        if kaithi_translation is None:
            print("📁 Word not found in CSV. Asking Gemini for translation...")
            kaithi_translation = translate_with_gemini(user_input)

        print(f"📝 Kaithi translation for '{user_input}': {kaithi_translation}")

# ✅ Start the Bot
bot_translate_to_kaithi()

from google.colab import drive
drive.mount('/content/drive')